export * from './handlers/general'
export * from './handlers/cardMethods'
export * from './handlers/newPerson'
export * from './handlers/checkIfRelativesConnectedWithoutPerson'
export * from '../src/AddRelativeTree/AddRelativeTree.AddRelative'
